// Generated by scripts/generate-app-compat-manifest.mjs from config/app-resource-history.json.
export const RETAINED_ACTIVITY_EXPLORER_HASHES = [
  "457443ca1623", // v0.8.3
  "383ddd6e2c61", // v0.8.4
] as const

export const RETAINED_ACTIVITY_EXPLORER_RESOURCE_URIS = RETAINED_ACTIVITY_EXPLORER_HASHES.map(
  (hash) => `ui://sqd/activity-explorer.${hash}.html`,
)
