import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { build } from 'esbuild'

const projectRoot = process.cwd()
const entryPoint = path.join(projectRoot, 'src/ui/index.tsx')
const outputModule = path.join(projectRoot, 'src/generated/portal-app.generated.ts')
const versionModule = path.join(projectRoot, 'src/generated/portal-app.version.ts')

const result = await build({
  entryPoints: [entryPoint],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  write: false,
  charset: 'utf8',
  sourcemap: false,
  minify: true,
  treeShaking: true,
  jsx: 'automatic',
  legalComments: 'none',
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  loader: {
    '.ts': 'ts',
    '.tsx': 'tsx',
    '.js': 'js',
  },
})

const bundle = result.outputFiles[0]?.text ?? ''
const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Portal Explorer</title>
  </head>
  <body>
    <div id="app"></div>
    <script>${bundle}</script>
  </body>
</html>`

// Derive a short content hash from the bundle so the MCP resource URI
// changes on every code-affecting build. MCP clients (Claude Desktop /
// Claude.ai) cache app HTML by resource URI — a stable URI means stale
// renders until the user manually refreshes. Hashing the bundle content
// makes cache-busting fully automatic.
const bundleHash = createHash('sha256').update(bundle).digest('hex').slice(0, 12)

await mkdir(path.dirname(outputModule), { recursive: true })
await writeFile(
  outputModule,
  `// This file is auto-generated by scripts/build-app-ui.mjs.\nexport const PORTAL_APP_HTML = ${JSON.stringify(html)} as const\n`,
  'utf8',
)
await writeFile(
  versionModule,
  `// This file is auto-generated by scripts/build-app-ui.mjs.\n// Content hash of the UI bundle — appended to the MCP resource URI so\n// every build gets a unique URI and clients always refetch.\nexport const PORTAL_APP_BUNDLE_HASH = ${JSON.stringify(bundleHash)} as const\n`,
  'utf8',
)

const sizeKb = (bundle.length / 1024).toFixed(1)
console.log(
  `Built Portal app bundle -> ${path.relative(projectRoot, outputModule)} (${sizeKb} KB, hash ${bundleHash})`,
)
