#!/usr/bin/env tsx
/* Records real SQD Portal tool results for the Explorer preview fixtures.

   Usage:
     tsx scripts/record-app-fixtures.ts                 # record live from Portal
     tsx scripts/record-app-fixtures.ts --from-json DIR # rebuild the module from saved JSON

   Requests live in scripts/app-fixture-requests.json. Every fixture the
   preview, the screenshot matrix, and the UI tests show is a recorded
   response from this server, so what people look at is real chain data. */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { Client } from '@modelcontextprotocol/client'
import { InMemoryTransport } from '@modelcontextprotocol/server'

import { createPortalServer } from '../src/server.ts'

const REQUESTS = path.resolve('scripts/app-fixture-requests.json')
const OUTPUT = path.resolve('src/app-ui/fixtures.recorded.ts')

type FixtureRequest = { tool: string; arguments: Record<string, unknown> }

async function recordLive(requests: Record<string, FixtureRequest>): Promise<Record<string, Record<string, unknown>>> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair()
  const server = createPortalServer({ transport: 'stdio', appEnabled: true })
  const client = new Client({ name: 'sqd-app-fixture-recorder', version: '1.0.0' })
  await server.connect(serverTransport)
  await client.connect(clientTransport)
  const recorded: Record<string, Record<string, unknown>> = {}
  try {
    const available = new Set((await client.listTools()).tools.map((tool) => tool.name))
    for (const [name, request] of Object.entries(requests)) {
      if (!available.has(request.tool)) throw new Error(`${name}: ${request.tool} is not registered`)
      const started = Date.now()
      const result = await client.callTool({ name: request.tool, arguments: request.arguments })
      const structured = result.structuredContent as Record<string, unknown> | undefined
      if (result.isError || !structured) throw new Error(`${name}: ${request.tool} did not return structured content`)
      recorded[name] = structured
      console.log(`OK  ${name}: ${request.tool} ${Date.now() - started}ms`)
    }
  } finally {
    await client.close()
    await server.close()
  }
  return recorded
}

async function loadJson(directory: string, names: string[]): Promise<Record<string, Record<string, unknown>>> {
  const recorded: Record<string, Record<string, unknown>> = {}
  for (const name of names) {
    recorded[name] = JSON.parse(await readFile(path.join(directory, `${name}.json`), 'utf8'))
  }
  return recorded
}

async function main() {
  const requests = JSON.parse(await readFile(REQUESTS, 'utf8')) as Record<string, FixtureRequest>
  const fromIndex = process.argv.indexOf('--from-json')
  const refreshIndex = process.argv.indexOf('--refresh')
  let recorded: Record<string, Record<string, unknown>>
  if (fromIndex >= 0) {
    const directory = process.argv[fromIndex + 1]
    if (refreshIndex >= 0) {
      /* Re-record only the named fixtures into the JSON directory. */
      const names = process.argv[refreshIndex + 1].split(',')
      const fresh = await recordLive(Object.fromEntries(names.map((name) => [name, requests[name]])))
      for (const [name, payload] of Object.entries(fresh))
        await writeFile(path.join(directory, `${name}.json`), JSON.stringify(payload, null, 2))
    }
    recorded = await loadJson(directory, Object.keys(requests))
  } else {
    recorded = await recordLive(requests)
  }
  const recordedAt = new Date().toISOString()
  const requestLines = Object.entries(requests).map(
    ([name, request]) => `//   ${name}: ${request.tool} ${JSON.stringify(request.arguments)}`,
  )
  const source = [
    '// Generated by scripts/record-app-fixtures.ts. Do not edit by hand.',
    `// Real SQD Portal responses recorded ${recordedAt} with these requests:`,
    ...requestLines,
    '',
    `export const RECORDED_FIXTURES_AT = ${JSON.stringify(recordedAt)}`,
    '',
    `export const RECORDED_FIXTURES: Record<string, Record<string, unknown>> = ${JSON.stringify(recorded, null, 1)}`,
    '',
  ].join('\n')
  await mkdir(path.dirname(OUTPUT), { recursive: true })
  await writeFile(OUTPUT, source)
  console.log(
    `Wrote ${path.relative(process.cwd(), OUTPUT)}: ${Object.keys(recorded).length} fixtures, ${Buffer.byteLength(source)} bytes`,
  )
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
